#!/bin/sh
# This pre-post git hook makes only basic check of a build.
# Please double check if you made a build over all you changes and committed it.
# Use --no-verify flag on your risk.

# checks if password-page/dist/ is the newest againts node_modules/ and src/ folders.
if [ `stat -f "%m" password-page/dist/` -ge `stat -f "%m" password-page/node_modules/` -a `stat -f "%m" password-page/dist/` -ge `stat -f "%m" password-page/src/` ] ; then
	# checks if dist/ id added and commited.
	if git status | grep /password-page/dist/ ; then
		echo "Please add and commit password-page/dist/ before push."
		exit 1
	else
		echo "Looks like password-page/dist/ is up to date. Pushing to origin..."
		exit 0
	fi
else
	echo "Looks like password-page/dist/ is NOT up to date."
	echo "Please do npm run build, add /password-page/dist/ and commit."
	exit 1
fi
