---
- name: 'Provision Agent'
  hosts: default
  become: true

  tasks:
    - name: Enable epel repo
      command: amazon-linux-extras install -y epel

    - name: Install packages
      package:
        name:
          - docker
          - java-1.8.0-openjdk.x86_64
          - git
          - jq
          - gettext
          - unzip
          - python3
          - mariadb # to be honest we need only client but centos doesn't have client package
          - chromium
          - bats
          - svn # we use it in pmm-framework.sh
          - php # we use PHP in pmm-qa repo
          - php-mysqlnd
          - php-pdo
          - https://rpm.nodesource.com/pub_14.x/el/7/x86_64/nodejs-14.18.1-1nodesource.x86_64.rpm
        state: present

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.2.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x,o+x'

    - name: Copy docker daemon config
      copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

    - name: Install kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.22.5/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 'u+x,g+x,o+x'

    - name: Download and unarchive installer
      unarchive:
        src: https://s3.amazonaws.com/aws-cli/awscli-bundle.zip
        dest: /tmp
        remote_src: yes

    - name: Install awscl
      shell: python3 /tmp/awscli-bundle/install

    - name: install npm
      command: npm install

    - name: Enable Docker service
      systemd:
        name: docker.service
        state: started
        enabled: yes

    - name: Add ec2-user user to "docker" group
      user:
        name: "ec2-user"
        groups:
          - "docker"
        append: yes

    - name: Turn off swap
      sysctl:
        name: vm.swappiness
        value: 0
        state: present

    - name: Increase dirty ratio
      sysctl:
        name: vm.dirty_ratio
        value: 80
        state: present

    - name: Decrease dirty_background_ratio
      sysctl:
        name: vm.dirty_background_ratio
        value: 5

    - name: Increase dirty_expire_centisecs
      sysctl:
        name: vm.dirty_expire_centisecs
        value: 12000 #120 sec

    - name: Increase net.core.somaxconn
      sysctl:
        name: net.core.somaxconn
        value: 1024

    - name: Increase net.core.netdev_max_backlog
      sysctl:
        name: net.core.netdev_max_backlog
        value: 5000

    - name: Increase net.core.rmem_max
      sysctl:
        name: net.core.rmem_max
        value: 16777216

    - name: Increase net.core.wmem_max
      sysctl:
        name: net.core.wmem_max
        value: 16777216

    - name: Increase net.ipv4.tcp_wmem
      sysctl:
        name: net.ipv4.tcp_wmem
        value: 4096 12582912 16777216

    - name: Increase net.ipv4.tcp_rmem
      sysctl:
        name: net.ipv4.tcp_rmem
        value: 4096 12582912 16777216

    - name: Increase net.ipv4.tcp_max_syn_backlog
      sysctl:
        name: net.ipv4.tcp_max_syn_backlog
        value: 8192

    - name: Disable net.ipv4.tcp_slow_start_after_idle
      sysctl:
        name: net.ipv4.tcp_slow_start_after_idle
        value: 0

    - name: Enable net.ipv4.tcp_tw_reuse
      sysctl:
        name: net.ipv4.tcp_tw_reuse
        value: 1

    - name: Change net.ipv4.ip_local_port_range
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: 10240 65535

    - name: Change TCP Congestion Control Algorithm (net.ipv4.tcp_congestion_control)
      sysctl:
        name: net.ipv4.tcp_congestion_control
        value: bbr

    - name: Change net.ipv4.tcp_syn_retries
      sysctl:
        name: net.ipv4.tcp_syn_retries
        value: 2

    - name: Change BBR algoritm
      sysctl:
        name: net.core.default_qdisc
        value: fq

    - name: Increase kernel.perf_event_max_stack
      sysctl:
        name: kernel.perf_event_max_stack
        value: 1023

    - name: Increase fs.xfs.xfssyncd_centisecs
      sysctl:
        name: fs.xfs.xfssyncd_centisecs
        value: 9000

    - name: Increase fs.inotify.max_user_watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: 1048576

    - name: Get disk UUID
      command: blkid -s UUID -o value /dev/nvme0n1p1
      register: disk_uuid

    - name: Replace fstab entities with new mount options
      lineinfile:
        path: /etc/fstab
        regexp: "^UUID={{ disk_uuid.stdout }}"
        line: "UUID={{ disk_uuid.stdout }}     /           xfs    defaults,noatime,nobarrier,discard  1   1"

    - name: Add vbox-01.ci.percona.com to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "10.30.6.220 vbox-01.ci.percona.com"
        state: present

    - name: Add repo.ci.percona.com to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        line: "10.30.6.9 repo.ci.percona.com"
        state: present
