---
# Initialize Postgres
    - name: Packages                   | Install percona-release rpm
      yum:
        name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
        state: installed

    - name: Postgres                   | Add PostgreSQL YUM repository
      yum_repository:
        name: percona-ppg-11
        description: PostgreSQL YUM repository - x86_64
        baseurl: http://repo.percona.com/ppg-11/yum/{{ ppg_repo_name }}/7/RPMS/x86_64
        gpgcheck: yes
        enabled: yes
        gpgkey: file:///etc/pki/rpm-gpg/PERCONA-PACKAGING-KEY

    - name: Postgres                   | Install Postgres
      yum:
        name:
          - percona-postgresql11-server
          - percona-postgresql11-contrib
          - percona-postgresql11
          - python-psycopg2
        state: installed
        enablerepo: "percona-ppg-11"

    - name: Postgres                   | Create Postgres data dir
      file: path={{ item }} state=directory owner=postgres group=postgres
      with_items:
        - /srv/postgres

    - name: Postgres                   | Create Postgres data cluster
      command: su postgres -c "/usr/pgsql-11/bin/initdb -D /srv/postgres"

    - name: Postgres                   | Disable logging_collector
      lineinfile:
        path: /srv/postgres/postgresql.conf
        regexp: '^logging_collector'
        line: 'logging_collector = off'
