---
    - name: Packages                   | Add Nginx repository
      yum_repository:
        name: nginx
        description: nginx repo
        baseurl: http://nginx.org/packages/mainline/centos/7/$basearch/
        gpgcheck: no
        enabled: yes

    - name: Install nginx rpm          | Install nginx rpm
      yum:
        name:
          - nginx-1.21.0
        state: installed

    - name: NGINX SSL Certificate      | Add script to generate ssl certificate
      copy:
        src: generate-ssl-certificate
        dest: /var/lib/cloud/scripts/per-boot/
        mode: 0755

    - name: NGINX SSL Certificate      | Check certificate file
      stat: path=/srv/nginx/certificate.crt
      register: certificate_file

    - name: NGINX SSL Certificate      | Generate certificate
      when: not certificate_file.stat.exists
      command: /var/lib/cloud/scripts/per-boot/generate-ssl-certificate

    - name: NGINX                      | Disable NGINX daemon
      lineinfile:
        dest: /etc/nginx/nginx.conf
        line: 'daemon off;'

    - name: NGINX                      | Change output for nginx error logs
      replace:
        dest: /etc/nginx/nginx.conf
        regexp: '/var/log/nginx/error\.log'
        replace: '/dev/stderr'

    - name: NGINX                      | Change output for nginx access logs
      replace:
        dest: /etc/nginx/nginx.conf
        regexp: '/var/log/nginx/access\.log'
        replace: '/dev/stdout'

    - name: NGINX                      | Remove '/etc/nginx/conf.d/default.conf'
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent

